package com.perceus.spellcasting2;

import java.util.HashMap;
import java.util.Map;

import org.bukkit.event.Listener;

import com.perceus.spellcasting2.accounts.*;
import com.perceus.spellcasting2.aethereal_spells.SpellAetherealOverride;
import com.perceus.spellcasting2.aethereal_spells.SpellAetherealOverridePlus;
import com.perceus.spellcasting2.aethereal_spells.SpellCleanse;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyAquaAffinity;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyBaneOfArthropods;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyBlastProtection;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyChanneling;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyDepthStrider;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyDurability;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyEfficiency;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyFeatherFalling;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyFireAspect;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyFireProtection;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyFishingLuck;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyFlame;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyFortune;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyFrostWalker;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyImpaling;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyInfinity;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyKnockback;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyLooting;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyLoyalty;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyLure;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyMending;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyMultishot;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyPiercing;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyPower;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyProjectileProtection;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyProtection;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyPunch;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyQuickCharge;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyRespiration;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyRipTide;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifySharpness;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifySilkTouch;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifySmite;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifySoulSpeed;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifySweepingEdge;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifySwiftSneak;
import com.perceus.spellcasting2.aethereal_spells.SpellFortifyThorns;
import com.perceus.spellcasting2.ancient_spells.SpellCreateAllay;
import com.perceus.spellcasting2.ancient_spells.SpellCreateAxolotl;
import com.perceus.spellcasting2.ancient_spells.SpellCreateBat;
import com.perceus.spellcasting2.ancient_spells.SpellCreateBee;
import com.perceus.spellcasting2.ancient_spells.SpellCreateBlaze;
import com.perceus.spellcasting2.ancient_spells.SpellCreateCaveSpider;
import com.perceus.spellcasting2.ancient_spells.SpellCreateChicken;
import com.perceus.spellcasting2.ancient_spells.SpellCreateCow;
import com.perceus.spellcasting2.ancient_spells.SpellCreateCreeper;
import com.perceus.spellcasting2.ancient_spells.SpellCreateDolphin;
import com.perceus.spellcasting2.ancient_spells.SpellCreateDonkey;
import com.perceus.spellcasting2.ancient_spells.SpellCreateDrowned;
import com.perceus.spellcasting2.ancient_spells.SpellCreateElderGuardian;
import com.perceus.spellcasting2.ancient_spells.SpellCreateEnderman;
import com.perceus.spellcasting2.ancient_spells.SpellCreateEvoker;
import com.perceus.spellcasting2.ancient_spells.SpellCreateFox;
import com.perceus.spellcasting2.ancient_spells.SpellCreateFrog;
import com.perceus.spellcasting2.ancient_spells.SpellCreateGhast;
import com.perceus.spellcasting2.ancient_spells.SpellCreateGlowSquid;
import com.perceus.spellcasting2.ancient_spells.SpellCreateGoat;
import com.perceus.spellcasting2.ancient_spells.SpellCreateGuardian;
import com.perceus.spellcasting2.ancient_spells.SpellCreateHoglin;
import com.perceus.spellcasting2.ancient_spells.SpellCreateHorse;
import com.perceus.spellcasting2.ancient_spells.SpellCreateHusk;
import com.perceus.spellcasting2.ancient_spells.SpellCreateIronGolem;
import com.perceus.spellcasting2.ancient_spells.SpellCreateLlama;
import com.perceus.spellcasting2.ancient_spells.SpellCreateMagmaCube;
import com.perceus.spellcasting2.ancient_spells.SpellCreateMooshroom;
import com.perceus.spellcasting2.ancient_spells.SpellCreateMule;
import com.perceus.spellcasting2.ancient_spells.SpellCreateOcelot;
import com.perceus.spellcasting2.ancient_spells.SpellCreatePanda;
import com.perceus.spellcasting2.ancient_spells.SpellCreateParrot;
import com.perceus.spellcasting2.ancient_spells.SpellCreatePhantom;
import com.perceus.spellcasting2.ancient_spells.SpellCreatePig;
import com.perceus.spellcasting2.ancient_spells.SpellCreatePiglin;
import com.perceus.spellcasting2.ancient_spells.SpellCreatePiglinBrute;
import com.perceus.spellcasting2.ancient_spells.SpellCreatePillager;
import com.perceus.spellcasting2.ancient_spells.SpellCreatePolarBear;
import com.perceus.spellcasting2.ancient_spells.SpellCreateRabbit;
import com.perceus.spellcasting2.ancient_spells.SpellCreateRavager;
import com.perceus.spellcasting2.ancient_spells.SpellCreateSheep;
import com.perceus.spellcasting2.ancient_spells.SpellCreateShulker;
import com.perceus.spellcasting2.ancient_spells.SpellCreateSkeleton;
import com.perceus.spellcasting2.ancient_spells.SpellCreateSlime;
import com.perceus.spellcasting2.ancient_spells.SpellCreateSnowGolem;
import com.perceus.spellcasting2.ancient_spells.SpellCreateSpider;
import com.perceus.spellcasting2.ancient_spells.SpellCreateSquid;
import com.perceus.spellcasting2.ancient_spells.SpellCreateStray;
import com.perceus.spellcasting2.ancient_spells.SpellCreateStrider;
import com.perceus.spellcasting2.ancient_spells.SpellCreateTurtle;
import com.perceus.spellcasting2.ancient_spells.SpellCreateVex;
import com.perceus.spellcasting2.ancient_spells.SpellCreateVindicator;
import com.perceus.spellcasting2.ancient_spells.SpellCreateWarden;
import com.perceus.spellcasting2.ancient_spells.SpellCreateWitch;
import com.perceus.spellcasting2.ancient_spells.SpellCreateWither;
import com.perceus.spellcasting2.ancient_spells.SpellCreateWitherSkeleton;
import com.perceus.spellcasting2.ancient_spells.SpellCreateWolf;
import com.perceus.spellcasting2.ancient_spells.SpellCreateZoglin;
import com.perceus.spellcasting2.ancient_spells.SpellCreateZombie;
import com.perceus.spellcasting2.ancient_spells.SpellCreateZombifiedPiglin;
import com.perceus.spellcasting2.astral_spells.SpellDesolate;
import com.perceus.spellcasting2.astral_spells.SpellSuspendedMatter;
import com.perceus.spellcasting2.darkmagic_spells.SpellBloodletting;
import com.perceus.spellcasting2.darkmagic_spells.SpellCurse;
import com.perceus.spellcasting2.darkmagic_spells.SpellDeath;
import com.perceus.spellcasting2.darkmagic_spells.SpellEtherBreak;
import com.perceus.spellcasting2.darkmagic_spells.SpellHex;
import com.perceus.spellcasting2.darkmagic_spells.SpellLawOfProgression;
import com.perceus.spellcasting2.fire_spells.SpellChaosFireball;
import com.perceus.spellcasting2.fire_spells.SpellChaosMeteor;
import com.perceus.spellcasting2.fire_spells.SpellCombustion;
import com.perceus.spellcasting2.fire_spells.SpellEmbers;
import com.perceus.spellcasting2.fire_spells.SpellEruption;
import com.perceus.spellcasting2.fire_spells.SpellExpulsion;
import com.perceus.spellcasting2.fire_spells.SpellFireball;
import com.perceus.spellcasting2.fire_spells.SpellFlamethrower;
import com.perceus.spellcasting2.fire_spells.SpellHellFire;
import com.perceus.spellcasting2.fire_spells.SpellIgnite;
import com.perceus.spellcasting2.fire_spells.SpellIgnitionDrive;
import com.perceus.spellcasting2.fire_spells.SpellInsulate;
import com.perceus.spellcasting2.fire_spells.SpellKindleFlame;
import com.perceus.spellcasting2.fire_spells.SpellLavaBomb;
import com.perceus.spellcasting2.fire_spells.SpellManaBurn;
import com.perceus.spellcasting2.fire_spells.SpellMeteor;
import com.perceus.spellcasting2.fire_spells.SpellOverclockProtocol;
import com.perceus.spellcasting2.fire_spells.SpellOverheat;
import com.perceus.spellcasting2.fire_spells.SpellSmokeScreen;
import com.perceus.spellcasting2.geo_spells.SpellBoulder;
import com.perceus.spellcasting2.geo_spells.SpellDracoMorph;
import com.perceus.spellcasting2.geo_spells.SpellEarthquake;
import com.perceus.spellcasting2.geo_spells.SpellGeoMorph;
import com.perceus.spellcasting2.geo_spells.SpellGravitas;
import com.perceus.spellcasting2.geo_spells.SpellInscribeLuck;
import com.perceus.spellcasting2.geo_spells.SpellMageMorph;
import com.perceus.spellcasting2.geo_spells.SpellMetalMorph;
import com.perceus.spellcasting2.geo_spells.SpellNaturesGift;
import com.perceus.spellcasting2.geo_spells.SpellNaturesWrath;
import com.perceus.spellcasting2.geo_spells.SpellNullify;
import com.perceus.spellcasting2.geo_spells.SpellPoisonCloud;
import com.perceus.spellcasting2.geo_spells.SpellPoisonGas;
import com.perceus.spellcasting2.geo_spells.SpellSandBlast;
import com.perceus.spellcasting2.geo_spells.SpellSandstorm;
import com.perceus.spellcasting2.geo_spells.SpellTerraform;
import com.perceus.spellcasting2.geo_spells.SpellTillEarth;
import com.perceus.spellcasting2.geo_spells.SpellToxicGas;
import com.perceus.spellcasting2.geo_spells.SpellTransmute;
import com.perceus.spellcasting2.holy_spells.SpellAccolades;
import com.perceus.spellcasting2.holy_spells.SpellAmeliorate;
import com.perceus.spellcasting2.holy_spells.SpellAngelicFlight;
import com.perceus.spellcasting2.holy_spells.SpellBarrier;
import com.perceus.spellcasting2.holy_spells.SpellCure;
import com.perceus.spellcasting2.holy_spells.SpellDisarm;
import com.perceus.spellcasting2.holy_spells.SpellEmitForce;
import com.perceus.spellcasting2.holy_spells.SpellEtherTransference;
import com.perceus.spellcasting2.holy_spells.SpellExpellUndead;
import com.perceus.spellcasting2.holy_spells.SpellExtricate;
import com.perceus.spellcasting2.holy_spells.SpellGuardianAngel;
import com.perceus.spellcasting2.holy_spells.SpellHeal;
import com.perceus.spellcasting2.holy_spells.SpellHealingHands;
import com.perceus.spellcasting2.holy_spells.SpellJudgement;
import com.perceus.spellcasting2.holy_spells.SpellLawOfRegression;
import com.perceus.spellcasting2.holy_spells.SpellLivingRecall;
import com.perceus.spellcasting2.holy_spells.SpellMagicBolt;
import com.perceus.spellcasting2.holy_spells.SpellPacify;
import com.perceus.spellcasting2.holy_spells.SpellPenance;
import com.perceus.spellcasting2.holy_spells.SpellProlongedFlight;
import com.perceus.spellcasting2.holy_spells.SpellRadiance;
import com.perceus.spellcasting2.holy_spells.SpellRegenerate;
import com.perceus.spellcasting2.holy_spells.SpellRestoration;
import com.perceus.spellcasting2.holy_spells.SpellSatiate;
import com.perceus.spellcasting2.lunar_spells.SpellLunarBolt;
import com.perceus.spellcasting2.lunar_spells.SpellLunarEclipse;
import com.perceus.spellcasting2.solar_spells.SpellComet;
import com.perceus.spellcasting2.solar_spells.SpellSolGate;
import com.perceus.spellcasting2.solar_spells.SpellSolarEclipse;
import com.perceus.spellcasting2.solar_spells.SpellSolarFlare;
import com.perceus.spellcasting2.spellitem_spell.MagicWeapon_WandOfFire;
import com.perceus.spellcasting2.spellitem_spell.MagicWeapon_WandOfGeo;
import com.perceus.spellcasting2.spellitem_spell.MagicWeapon_WandOfHoly;
import com.perceus.spellcasting2.spellitem_spell.MagicWeapon_WandOfStorm;
import com.perceus.spellcasting2.spellitem_spell.MagicWeapon_WandOfUnholy;
import com.perceus.spellcasting2.spellitem_spell.MagicWeapon_WandOfVoid;
import com.perceus.spellcasting2.spellitem_spell.MagicWeapon_WandOfWater;
import com.perceus.spellcasting2.spellitem_spell.SpellItem_AetherealScroll;
import com.perceus.spellcasting2.spellitem_spell.SpellItem_AetherealScrollPlus;
import com.perceus.spellcasting2.spellitem_spell.SpellItem_BloodCrystal;
import com.perceus.spellcasting2.spellitem_spell.SpellItem_BloodCrystalPlus;
import com.perceus.spellcasting2.spellitem_spell.SpellItem_Fireball;
import com.perceus.spellcasting2.spellitem_spell.SpellItem_HealthCrystal;
import com.perceus.spellcasting2.spellitem_spell.SpellItem_ManaCrystal;
import com.perceus.spellcasting2.spellitem_spell.SpellItem_ProtectivePaste;
import com.perceus.spellcasting2.spellitem_spell.SpellItem_SmokeBomb;
import com.perceus.spellcasting2.spellitem_spell.SpellItem_Updraft;
import com.perceus.spellcasting2.spellitem_spell.SpellItem_XpCrystal;
import com.perceus.spellcasting2.storm_spells.SpellArcaneBolt;
import com.perceus.spellcasting2.storm_spells.SpellBlink;
import com.perceus.spellcasting2.storm_spells.SpellElectrocute;
import com.perceus.spellcasting2.storm_spells.SpellExplosiveBolt;
import com.perceus.spellcasting2.storm_spells.SpellGaleForce;
import com.perceus.spellcasting2.storm_spells.SpellGalvanicNeedle;
import com.perceus.spellcasting2.storm_spells.SpellGust;
import com.perceus.spellcasting2.storm_spells.SpellSmite;
import com.perceus.spellcasting2.storm_spells.SpellSoothingCurrent;
import com.perceus.spellcasting2.storm_spells.SpellStaticCharge;
import com.perceus.spellcasting2.storm_spells.SpellStormSurge;
import com.perceus.spellcasting2.storm_spells.SpellTailWind;
import com.perceus.spellcasting2.storm_spells.SpellThunderStorm;
import com.perceus.spellcasting2.storm_spells.SpellThunderStrike;
import com.perceus.spellcasting2.storm_spells.SpellUberCharge;
import com.perceus.spellcasting2.storm_spells.SpellVaporize;
import com.perceus.spellcasting2.storm_spells.SpellWildBolt;
import com.perceus.spellcasting2.unholy_spells.SpellDarkHarvest;
import com.perceus.spellcasting2.unholy_spells.SpellDebilitate;
import com.perceus.spellcasting2.unholy_spells.SpellDemonSight;
import com.perceus.spellcasting2.unholy_spells.SpellDemonicReflexes;
import com.perceus.spellcasting2.unholy_spells.SpellDoom;
import com.perceus.spellcasting2.unholy_spells.SpellDrainingAura;
import com.perceus.spellcasting2.unholy_spells.SpellEmitDamagingForce;
import com.perceus.spellcasting2.unholy_spells.SpellExpellLiving;
import com.perceus.spellcasting2.unholy_spells.SpellLifeSteal;
import com.perceus.spellcasting2.unholy_spells.SpellLightShift;
import com.perceus.spellcasting2.unholy_spells.SpellRaiseDead;
import com.perceus.spellcasting2.unholy_spells.SpellReapAndSew;
import com.perceus.spellcasting2.unholy_spells.SpellReapSouls;
import com.perceus.spellcasting2.unholy_spells.SpellRot;
import com.perceus.spellcasting2.unholy_spells.SpellSapEther;
import com.perceus.spellcasting2.unholy_spells.SpellUndeadEffigy;
import com.perceus.spellcasting2.unholy_spells.SpellUndeadRecall;
import com.perceus.spellcasting2.void_spells.SpellAccelerateLife;
import com.perceus.spellcasting2.void_spells.SpellAntiGravity;
import com.perceus.spellcasting2.void_spells.SpellAntimatter;
import com.perceus.spellcasting2.void_spells.SpellBanishGreaterEvil;
import com.perceus.spellcasting2.void_spells.SpellCataclysm;
import com.perceus.spellcasting2.void_spells.SpellCrush;
import com.perceus.spellcasting2.void_spells.SpellEtherContinuity;
import com.perceus.spellcasting2.void_spells.SpellGate;
import com.perceus.spellcasting2.void_spells.SpellNullPointConfiguration;
import com.perceus.spellcasting2.void_spells.SpellOverrideClimate;
import com.perceus.spellcasting2.void_spells.SpellPolarize;
import com.perceus.spellcasting2.void_spells.SpellPrimordialShift;
import com.perceus.spellcasting2.void_spells.SpellPull;
import com.perceus.spellcasting2.void_spells.SpellRecallAnchor;
import com.perceus.spellcasting2.void_spells.SpellRift;
import com.perceus.spellcasting2.void_spells.SpellSingularity;
import com.perceus.spellcasting2.void_spells.SpellTelekinesis;
import com.perceus.spellcasting2.void_spells.SpellTeleport;
import com.perceus.spellcasting2.void_spells.SpellVectorPlate;
import com.perceus.spellcasting2.void_spells.SpellVoidBurst;
import com.perceus.spellcasting2.void_spells.SpellVoidContainment;
import com.perceus.spellcasting2.void_spells.SpellVoidGate;
import com.perceus.spellcasting2.void_spells.SpellVoidShift;
import com.perceus.spellcasting2.water_spells.SpellBlizzard;
import com.perceus.spellcasting2.water_spells.SpellConduitEther;
import com.perceus.spellcasting2.water_spells.SpellCrystalize;
import com.perceus.spellcasting2.water_spells.SpellFishScales;
import com.perceus.spellcasting2.water_spells.SpellFrostBite;
import com.perceus.spellcasting2.water_spells.SpellGills;
import com.perceus.spellcasting2.water_spells.SpellIceAge;
import com.perceus.spellcasting2.water_spells.SpellMendingWater;
import com.perceus.spellcasting2.water_spells.SpellPoseidonsGift;
import com.perceus.spellcasting2.water_spells.SpellRagingCurrent;
import com.perceus.spellcasting2.water_spells.SpellReconstitute;
import com.perceus.spellcasting2.water_spells.SpellRipTide;
import com.perceus.spellcasting2.water_spells.SpellSaturate;
import com.perceus.spellcasting2.water_spells.SpellSoak;
import com.perceus.spellcasting2.water_spells.SpellSplash;
import com.perceus.spellcasting2.water_spells.SpellSuffocate;
import com.perceus.spellcasting2.water_spells.SpellTidalForce;
import com.perceus.spellcasting2.water_spells.SpellWaveWake;

public class CastListener implements Listener
{
	@SuppressWarnings("serial")
	public static Map<String, BaseSpellCapsule> spell_registry = new HashMap<>()
	{{
		//fire spells
		put("SpellFireBall", new SpellFireball()); 
		put("SpellChaosFireball", new SpellChaosFireball());
		put("SpellIgnite", new SpellIgnite());
		put("SpellKindleFlame", new SpellKindleFlame());
		put("SpellOverheat", new SpellOverheat());
		put("SpellMeteor", new SpellMeteor());
		put("SpellChaosMeteor", new SpellChaosMeteor());
		put("SpellOverclockProtocol", new SpellOverclockProtocol());
		put("SpellSmokescreen", new SpellSmokeScreen());
		put("SpellSolGate", new SpellSolGate()); 
		put("SpellFlamethrower", new SpellFlamethrower());
		put("SpellInsulate", new SpellInsulate());
		put("SpellIgnitionDrive", new SpellIgnitionDrive());
		put("SpellManaBurn", new SpellManaBurn());
		put("SpellHellFire", new SpellHellFire());
		put("SpellCombustion", new SpellCombustion());
		put("SpellEmbers", new SpellEmbers());
		put("SpellSolarFlare", new SpellSolarFlare());
		put("SpellExpulsion", new SpellExpulsion());
		put("SpellComet", new SpellComet());
		put("SpellLavaBomb", new SpellLavaBomb());
		put("SpellEruption", new SpellEruption());
		
		//holy spells
		put("SpellLawOfRegression", new SpellLawOfRegression());
		put("SpellHeal", new SpellHeal()); 
		put("SpellHealingHands", new SpellHealingHands()); 
		put("SpellBarrier", new SpellBarrier()); 
		put("SpellAngelicFlight", new SpellAngelicFlight()); 
		put("SpellGuardianAngel", new SpellGuardianAngel()); 
		put("SpellMagicBolt", new SpellMagicBolt()); 
		put("SpellSatiate", new SpellSatiate()); 
		put("SpellRadiance", new SpellRadiance()); 
		put("SpellJudgement", new SpellJudgement()); 
		put("SpellCure", new SpellCure()); 
		put("SpellAccolades", new SpellAccolades()); 
		put("SpellExpellUndead", new SpellExpellUndead());
		put("SpellExtricate", new SpellExtricate()); 
		put("SpellRegenerate", new SpellRegenerate()); 
		put("SpellEmitForce", new SpellEmitForce()); 
		put("SpellPenance", new SpellPenance());
		put("SpellProlongedFlight", new SpellProlongedFlight());
		put("SpellAmeliorate", new SpellAmeliorate());
		put("SpellPacify", new SpellPacify());
		put("SpellDisarm", new SpellDisarm());
		put("SpellLivingRecall", new SpellLivingRecall());
		put("SpellRestoration", new SpellRestoration());
		put("SpellEtherTransference", new SpellEtherTransference());
		
		//void spells
		put("SpellBanishGreaterEvil", new SpellBanishGreaterEvil());
		put("SpellTeleport", new SpellTeleport());
		put("SpellRift", new SpellRift());
		put("SpellGate", new SpellGate());
		put("SpellVoidGate", new SpellVoidGate());
		put("SpellPull", new SpellPull());
		put("SpellCrush", new SpellCrush());
		put("SpellVectorPlate", new SpellVectorPlate());
		put("SpellAccelerateLife", new SpellAccelerateLife());
		put("SpellPolarize", new SpellPolarize());
		put("SpellVoidBurst", new SpellVoidBurst());
		put("SpellAntiGravity", new SpellAntiGravity());
		put("SpellAntimatter", new SpellAntimatter());
		put("SpellCataclysm", new SpellCataclysm());
		put("SpellPrimordialShift", new SpellPrimordialShift());
		put("SpellOverrideClimate", new SpellOverrideClimate());
		put("SpellVoidShift", new SpellVoidShift());
		put("SpellNullPointConfiguration", new SpellNullPointConfiguration());
		put("SpellVoidContainment", new SpellVoidContainment());
		put("SpellEtherContinuity", new SpellEtherContinuity());
		put("SpellRecallAnchor", new SpellRecallAnchor());
		put("SpellTelekinesis", new SpellTelekinesis());
		put("SpellSingularity", new SpellSingularity());
		
		//geo spells
		put("SpellGeoMorph", new SpellGeoMorph());
		put("SpellTerraform", new SpellTerraform());
		put("SpellMetalMorph", new SpellMetalMorph());
		put("SpellDracoMorph", new SpellDracoMorph());
		put("SpellMageMorph", new SpellMageMorph());
		put("SpellPoisonGas", new SpellPoisonGas());
		put("SpellToxicGas", new SpellToxicGas());
		put("SpellPoisonCloud", new SpellPoisonCloud());
		put("SpellBoulder", new SpellBoulder());
		put("SpellEarthquake", new SpellEarthquake());
		put("SpellNullify", new SpellNullify());
		put("SpellInscribeLuck", new SpellInscribeLuck());
		put("SpellGravitas", new SpellGravitas());
		put("SpellNaturesGift", new SpellNaturesGift());
		put("SpellNaturesWrath", new SpellNaturesWrath());
		put("SpellSandBlast", new SpellSandBlast());
		put("SpellSandstorm", new SpellSandstorm());
		put("SpellTransmute", new SpellTransmute());
		put("SpellTillEarth", new SpellTillEarth());
		
		//water spells
		put("SpellRipTide", new SpellRipTide()); 
		put("SpellMendingWater", new SpellMendingWater());
		put("SpellReconstitute", new SpellReconstitute());
		put("SpellGills", new SpellGills());
		put("SpellPoseidonsGift", new SpellPoseidonsGift());
		put("SpellSaturate", new SpellSaturate());
		put("SpellRagingCurrent", new SpellRagingCurrent());
		put("SpellSuffocate", new SpellSuffocate());
		put("SpellCrystalize", new SpellCrystalize());
		put("SpellTidalForce", new SpellTidalForce());
		put("SpellSplash", new SpellSplash());
		put("SpellSoak", new SpellSoak());
		put("SpellConduitEther", new SpellConduitEther());
		put("SpellFishScales", new SpellFishScales());
		put("SpellWaveWake", new SpellWaveWake());
		put("SpellFrostBite", new SpellFrostBite());
		put("SpellBlizzard", new SpellBlizzard());
		put("SpellIceAge", new SpellIceAge());
		
		//unholy spells
		put("SpellLifeSteal", new SpellLifeSteal());
		put("SpellUndeadEffigy", new SpellUndeadEffigy());
		put("SpellDoom", new SpellDoom());
		put("SpellRaiseDead", new SpellRaiseDead());
		put("SpellEmitDamagingForce", new SpellEmitDamagingForce());
		put("SpellDebilitate", new SpellDebilitate());
		put("SpellReapSouls", new SpellReapSouls());
		put("SpellRot", new SpellRot());
		put("SpellDemonicReflexes", new SpellDemonicReflexes());
		put("SpellDemonSight", new SpellDemonSight());
		put("SpellLightShift", new SpellLightShift());
		put("SpellDarkHarvest", new SpellDarkHarvest());
		put("SpellExpellLiving", new SpellExpellLiving());
		put("SpellSapEther", new SpellSapEther());
		put("SpellDrainingAura", new SpellDrainingAura());
		put("SpellUndeadRecall", new SpellUndeadRecall());
		put("SpellReapAndSew", new SpellReapAndSew());
		
		//storm spells
		put("SpellSmite", new SpellSmite());
		put("SpellBlink", new SpellBlink());
		put("SpellGust", new SpellGust());
		put("SpellGaleForce", new SpellGaleForce());
		put("SpellGalvanicNeedle", new SpellGalvanicNeedle());
		put("SpellStormSurge", new SpellStormSurge());
		put("SpellSoothingCurrent", new SpellSoothingCurrent());
		put("SpellThunderStorm", new SpellThunderStorm());
		put("SpellTailWind", new SpellTailWind());
		put("SpellStaticCharge", new SpellStaticCharge());
		put("SpellUberCharge", new SpellUberCharge());
		put("SpellThunderStrike", new SpellThunderStrike());
		put("SpellVaporize", new SpellVaporize());
		put("SpellWildBolt", new SpellWildBolt());
		put("SpellExplosiveBolt", new SpellExplosiveBolt());
		put("SpellArcaneBolt", new SpellArcaneBolt());
		put("SpellElectrocute", new SpellElectrocute());
		
		//dark magic spells
		put("SpellBloodletting", new SpellBloodletting());
		put("SpellEtherBreak", new SpellEtherBreak());
		put("SpellCurse", new SpellCurse());
		put("SpellHex", new SpellHex());
		put("SpellDeath", new SpellDeath());
		put("SpellLawOfProgression", new SpellLawOfProgression());
		
		//weapons
		put("MagicWeaponWandOfFire", new MagicWeapon_WandOfFire());
		put("MagicWeaponWandOfGeo", new MagicWeapon_WandOfGeo());
		put("MagicWeaponWandOfUnholy", new MagicWeapon_WandOfUnholy());
		put("MagicWeaponWandOfHoly", new MagicWeapon_WandOfHoly());
		put("MagicWeaponWandOfWater", new MagicWeapon_WandOfWater());
		put("MagicWeaponWandOfVoid", new MagicWeapon_WandOfVoid());
		put("MagicWeaponWandOfStorm", new MagicWeapon_WandOfStorm());
		
		//spell items
		put("SpellItem_Fireball", new SpellItem_Fireball());
		put("SpellItem_ManaCrystal", new SpellItem_ManaCrystal());
		put("SpellItem_ProtectivePaste", new SpellItem_ProtectivePaste());
		put("SpellItem_HealthCrystal", new SpellItem_HealthCrystal());
		put("SpellItem_SmokeBomb", new SpellItem_SmokeBomb());
		put("SpellItem_XpCrystal", new SpellItem_XpCrystal());
		put("SpellItem_Updraft", new SpellItem_Updraft());
		put("SpellItem_AetherealScroll", new SpellItem_AetherealScroll());
		put("SpellItem_AetherealScrollPlus", new SpellItem_AetherealScrollPlus());
		put("SpellItem_BloodCrystal", new SpellItem_BloodCrystal());
		put("SpellItem_BloodCrystalPlus", new SpellItem_BloodCrystalPlus());
		
		//aethereal spells
		put("SpellFortifyDurability", new SpellFortifyDurability());
		put("SpellFortifyMending", new SpellFortifyMending());
		put("SpellFortifySharpness", new SpellFortifySharpness());
		put("SpellFortifyEfficiency", new SpellFortifyEfficiency());
		put("SpellFortifySilkTouch", new SpellFortifySilkTouch());
		put("SpellFortifyFortune", new SpellFortifyFortune());
		put("SpellFortifyLure", new SpellFortifyLure());
		put("SpellFortifyFishingLuck", new SpellFortifyFishingLuck());
		put("SpellFortifyProtection", new SpellFortifyProtection());
		put("SpellCleanse", new SpellCleanse());
		put("SpellFortifyFireProtection", new SpellFortifyFireProtection());
		put("SpellFortifyBlastProtection", new SpellFortifyBlastProtection());
		put("SpellFortifyProjectileProtection", new SpellFortifyProjectileProtection());
		put("SpellFortifyFeatherFalling", new SpellFortifyFeatherFalling());
		put("SpellFortifyThorns", new SpellFortifyThorns());
		put("SpellFortifyRespiration", new SpellFortifyRespiration());
		put("SpellFortifyAquaAffinity", new SpellFortifyAquaAffinity());
		put("SpellFortifySwiftSneak", new SpellFortifySwiftSneak());
		put("SpellFortifyDepthStrider", new SpellFortifyDepthStrider());
		put("SpellFortifyFrostWalker", new SpellFortifyFrostWalker());
		put("SpellFortifySoulSpeed", new SpellFortifySoulSpeed());
		put("SpellFortifySmite", new SpellFortifySmite());
		put("SpellFortifyBaneOfArthropods", new SpellFortifyBaneOfArthropods());
		put("SpellFortifyLooting", new SpellFortifyLooting());
		put("SpellFortifySweepingEdge", new SpellFortifySweepingEdge());
		put("SpellFortifyKnockback", new SpellFortifyKnockback());
		put("SpellFortifyFireAspect", new SpellFortifyFireAspect());
		put("SpellFortifyPower", new SpellFortifyPower());
		put("SpellFortifyPunch", new SpellFortifyPunch());
		put("SpellFortifyInfinity", new SpellFortifyInfinity());
		put("SpellFortifyFlame", new SpellFortifyFlame());
		put("SpellFortifyMultishot", new SpellFortifyMultishot());
		put("SpellFortifyQuickCharge", new SpellFortifyQuickCharge());
		put("SpellFortifyPiercing", new SpellFortifyPiercing());
		put("SpellFortifyChanneling", new SpellFortifyChanneling());
		put("SpellFortifyImpaling", new SpellFortifyImpaling());
		put("SpellFortifyLoyalty", new SpellFortifyLoyalty());
		put("SpellFortifyRipTide", new SpellFortifyRipTide());
		put("SpellAetherealOverride", new SpellAetherealOverride());
		put("SpellAetherealOverridePlus", new SpellAetherealOverridePlus());
		
		//ancient spells
		put("SpellCreateCow", new SpellCreateCow());
		put("SpellCreateChicken", new SpellCreateChicken());
		put("SpellCreatePig", new SpellCreatePig());
		put("SpellCreateSheep", new SpellCreateSheep());
		put("SpellCreateRabbit", new SpellCreateRabbit());
		put("SpellCreateZombie", new SpellCreateZombie());
		put("SpellCreateAllay", new SpellCreateAllay());
		put("SpellCreateAxolotl", new SpellCreateAxolotl());
		put("SpellCreateBat", new SpellCreateBat());
		put("SpellCreateBee", new SpellCreateBee());
		put("SpellCreateDolphin", new SpellCreateDolphin());
		put("SpellCreateDonkey", new SpellCreateDonkey());
		put("SpellCreateFox", new SpellCreateFox());
		put("SpellCreateFrog", new SpellCreateFrog());
		put("SpellCreateHorse", new SpellCreateHorse());
		put("SpellCreateGoat", new SpellCreateGoat());
		put("SpellCreateLlama", new SpellCreateLlama());
		put("SpellCreateMooshroom", new SpellCreateMooshroom());
		put("SpellCreateMule", new SpellCreateMule());
		put("SpellCreateOcelot", new SpellCreateOcelot());
		put("SpellCreatePanda", new SpellCreatePanda());
		put("SpellCreateParrot", new SpellCreateParrot());
		put("SpellCreatePolarBear", new SpellCreatePolarBear());
		put("SpellCreateSquid", new SpellCreateSquid());
		put("SpellCreateTurtle", new SpellCreateTurtle());
		put("SpellCreateWolf", new SpellCreateWolf());
		put("SpellCreateCaveSpider", new SpellCreateCaveSpider());
		put("SpellCreateCreeper", new SpellCreateCreeper());
		put("SpellCreateDrowned", new SpellCreateDrowned());
		put("SpellCreateEnderman", new SpellCreateEnderman());
		put("SpellCreateEvoker", new SpellCreateEvoker());
		put("SpellCreateGlowSquid", new SpellCreateGlowSquid());
		put("SpellCreateGhast", new SpellCreateGhast());
		put("SpellCreateGuardian", new SpellCreateGuardian());
		put("SpellCreateHoglin", new SpellCreateHoglin());
		put("SpellCreateHusk", new SpellCreateHusk());
		put("SpellCreateMagmaCube", new SpellCreateMagmaCube());
		put("SpellCreatePhantom", new SpellCreatePhantom());
		put("SpellCreatePiglin", new SpellCreatePiglin());
		put("SpellCreatePiglinBrute", new SpellCreatePiglinBrute());
		put("SpellCreateRavager", new SpellCreateRavager());
		put("SpellCreatePillager", new SpellCreatePillager());
		put("SpellCreateShulker", new SpellCreateShulker());
		put("SpellCreateSkeleton", new SpellCreateSkeleton());
		put("SpellCreateSlime", new SpellCreateSlime());
		put("SpellCreateSpider", new SpellCreateSpider());
		put("SpellCreateStray", new SpellCreateStray());
		put("SpellCreateStrider", new SpellCreateStrider());
		put("SpellCreateBlaze", new SpellCreateBlaze());
		put("SpellCreateVex", new SpellCreateVex());
		put("SpellCreateVindicator", new SpellCreateVindicator());
		put("SpellCreateWitch", new SpellCreateWitch());
		put("SpellCreateWitherSkeleton", new SpellCreateWitherSkeleton());
		put("SpellCreateZoglin", new SpellCreateZoglin());
		put("SpellCreateZombifiedPiglin", new SpellCreateZombifiedPiglin());
		put("SpellCreateIronGolem", new SpellCreateIronGolem());
		put("SpellCreateSnowGolem", new SpellCreateSnowGolem());
		put("SpellCreateWither", new SpellCreateWither());
		put("SpellCreateWarden", new SpellCreateWarden());
		put("SpellCreateElderGuardian", new SpellCreateElderGuardian());
		
		//Knowledge Books
		put("KBSpellKindleFlame", new KBSpellKindleFlame());
		put("KBSpellEmbers", new KBSpellEmbers());
		put("KBSpellIgnite", new KBSpellIgnite());
		put("KBSpellFireBall", new KBSpellFireball());
		put("KBSpellExpulsion", new KBSpellExpulsion());
		put("KBSpellOverclockProtocol", new KBSpellOverclockProtocol());
		put("KBSpellSmokescreen", new KBSpellSmokescreen());
		put("KBSpellFlamethrower", new KBSpellFlamethrower());
		put("KBSpellInsulate", new KBSpellInsulate());
		put("KBSpellMeteor", new KBSpellMeteor());
		put("KBSpellCombustion", new KBSpellCombustion());
		put("KBSpellHellFire", new KBSpellHellFire());
		put("KBSpellIgnitionDrive", new KBSpellIgnitionDrive());
		put("KBSpellManaBurn", new KBSpellManaBurn());
		put("KBSpellRipTide", new KBSpellRipTide());
		put("KBSpellReconstitute", new KBSpellReconstitute());
		put("KBSpellTidalForce", new KBSpellTidalForce());
		put("KBSpellFishScales", new KBSpellFishScales());
		put("KBSpellSoak", new KBSpellSoak());
		put("KBSpellSaturate", new KBSpellSaturate());
		put("KBSpellWaveWake", new KBSpellWaveWake());
		put("KBSpellRagingCurrent", new KBSpellRagingCurrent());
		put("KBSpellGills", new KBSpellGills());
		put("KBSpellConduitEther", new KBSpellConduitEther());
		put("KBSpellSuffocate", new KBSpellSuffocate());
		put("KBSpellMendingWater", new KBSpellMendingWater());
		put("KBSpellCrystalize", new KBSpellCrystalize());
		put("KBSpellSplash", new KBSpellSplash());
		put("KBSpellTerraform", new KBSpellTerraform());
		put("KBSpellGeoMorph", new KBSpellGeoMorph());
		put("KBSpellSandBlast", new KBSpellSandBlast());
		put("KBSpellGravitas", new KBSpellGravitas());
		put("KBSpellMageMorph", new KBSpellMageMorph());
		put("KBSpellPoisonGas", new KBSpellPoisonGas());
		put("KBSpellMetalMorph", new KBSpellMetalMorph());
		put("KBSpellBoulder", new KBSpellBoulder());
		put("KBSpellToxicGas", new KBSpellToxicGas());
		put("KBSpellPoisonCloud", new KBSpellPoisonCloud());
		put("KBSpellDracoMorph", new KBSpellDracoMorph());
		put("KBSpellNaturesGift", new KBSpellNaturesGift());
		put("KBSpellNaturesWrath", new KBSpellNaturesWrath());
		put("KBSpellEarthquake", new KBSpellEarthquake());
		put("KBSpellGust", new KBSpellGust());
		put("KBSpellBlink", new KBSpellBlink());
		put("KBSpellGaleForce", new KBSpellGaleForce());
		put("KBSpellStaticCharge", new KBSpellStaticCharge());
		put("KBSpellSoothingCurrent", new KBSpellSoothingCurrent());
		put("KBSpellSmite", new KBSpellSmite());
		put("KBSpellGalvanicNeedle", new KBSpellGalvanicNeedle());
		put("KBSpellUberCharge", new KBSpellUberCharge());
		put("KBSpellThunderStorm", new KBSpellThunderStorm());
		put("KBSpellThunderStrike", new KBSpellThunderStrike());
		put("KBSpellExplosiveBolt", new KBSpellExplosiveBolt());
		put("KBSpellVaporize", new KBSpellVaporize());
		put("KBSpellArcaneBolt", new KBSpellArcaneBolt());
		put("KBSpellTailWind", new KBSpellTailWind());
		put("KBSpellVoidBurst", new KBSpellVoidBurst());
		put("KBSpellPull", new KBSpellPull());
		put("KBSpellVectorPlate", new KBSpellVectorPlate());
		put("KBSpellTeleport", new KBSpellTeleport());
		put("KBSpellAntiGravity", new KBSpellAntiGravity());
		put("KBSpellRift", new KBSpellRift());
		put("KBSpellAntimatter", new KBSpellAntimatter());
		put("KBSpellCrush", new KBSpellCrush());
		put("KBSpellPolarize", new KBSpellPolarize());
		put("KBSpellAccelerateLife", new KBSpellAccelerateLife());
		put("KBSpellCataclysm", new KBSpellCataclysm());
		put("KBSpellGate", new KBSpellGate());
		put("KBSpellVoidGate", new KBSpellVoidGate());
		put("KBSpellBanishGreaterEvil", new KBSpellBanishGreaterEvil());
		put("KBSpellLifeSteal", new KBSpellLifeSteal());
		put("KBSpellDemonicReflexes", new KBSpellDemonicReflexes());
		put("KBSpellDemonSight", new KBSpellDemonSight());
		put("KBSpellEmitDamagingForce", new KBSpellEmitDamagingForce());
		put("KBSpellDoom", new KBSpellDoom());
		put("KBSpellLightShift", new KBSpellLightShift());
		put("KBSpellReapSouls", new KBSpellReapSouls());
		put("KBSpellExpellLiving", new KBSpellExpellLiving());
		put("KBSpellRot", new KBSpellRot());
		put("KBSpellDebilitate", new KBSpellDebilitate());
		put("KBSpellDarkHarvest", new KBSpellDarkHarvest());
		put("KBSpellUndeadEffigy", new KBSpellUndeadEffigy());
		put("KBSpellRaiseDead", new KBSpellRaiseDead());
		put("KBSpellSapEther", new KBSpellSapEther());
		put("KBSpellEmitForce", new KBSpellEmitForce());
		put("KBSpellMagicBolt", new KBSpellMagicBolt());
		put("KBSpellHealingHands", new KBSpellHealingHands());
		put("KBSpellBarrier", new KBSpellBarrier());
		put("KBSpellCure", new KBSpellCure());
		put("KBSpellSatiate", new KBSpellSatiate());
		put("KBSpellLawOfRegression", new KBSpellLawOfRegression());
		put("KBSpellExpellUndead", new KBSpellExpellUndead());
		put("KBSpellAngelicFlight", new KBSpellAngelicFlight());
		put("KBSpellRegenerate", new KBSpellRegenerate());
		put("KBSpellAccolades", new KBSpellAccolades());
		put("KBSpellExtricate", new KBSpellExtricate());
		put("KBSpellPenance", new KBSpellPenance());
		put("KBSpellJudgement", new KBSpellJudgement());
		
		//dev items
		put("SpellResetTome", new SpellResetTome());
		put("SpellUnlockTome", new SpellUnlockTome());	
		
		//astral spells
		put("SpellDesolate", new SpellDesolate());
		put("SpellSuspendedMatter", new SpellSuspendedMatter());
		
		//lunar spells
		put("SpellLunarBolt", new SpellLunarBolt());
		put("SpellLunarEclipse", new SpellLunarEclipse());
		
		//solar spell
		put("SpellSolarEclipse", new SpellSolarEclipse());
		
	}};
	
}
